---
title: "SiblingsStudy_SupplementaryData"
author: "Catherine Laing & Elika Bergelson"
date: "13/02/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setup, include = FALSE}
library(tidyverse)
library(dplyr)
library(tibble)
library(lmerTest)
library(afex)
library(citr)

source("DataGathering.R")
```

## Effect of siblings on infants' input - audio recordings

### Parental Input

```{r speaker.type model, message=FALSE, warning=FALSE}

#shapiro.test(speaker.type$n) # not normal

speaker.type.model_audio <- lmerTest::lmer(Log.n ~ SibGroup + Speaker + (1|subj), data=subset(speaker.type, audio_video == "audio" & 
                                                                                           Speaker != "Family.input"), REML=FALSE)
speaker.type.model.null_audio <- lmerTest::lmer(Log.n ~ Speaker + (1|subj), data=subset(speaker.type, audio_video == "audio" & 
                                                                                           Speaker != "Family.input"), REML=FALSE)

anova(speaker.type.model_audio, speaker.type.model.null_audio) # p<.001

speaker.type.mean_audio <- speaker.type %>% 
  filter(audio_video == "audio" & Speaker == "Family.input") %>%
  group_by(subj) %>% 
  mutate(MeanN = mean(n)) %>% 
  filter(month == 17) 

speaker.type_wilcox_none_one_audio <- wilcox.test(
  x = subset(speaker.type.mean_audio, SibGroup == "None" & audio_video == "audio")$MeanN
  , y = subset(speaker.type.mean_audio, SibGroup == "One"  & audio_video == "audio")$MeanN
  , paired = FALSE
) # NS

speaker.type_wilcox_one_two_audio <- wilcox.test(
  x = subset(speaker.type.mean_audio, SibGroup == "2+" & audio_video == "audio")$MeanN
  , y = subset(speaker.type.mean_audio, SibGroup == "One" & audio_video == "audio")$MeanN
  , paired = FALSE
) # p=.02

```

```{r Sibling input, message=FALSE, warning=FALSE}

# Difference in amount of input from siblings

speaker.type.SIB_audio <- speaker.type %>% group_by(subj) %>% 
  filter(Speaker == "SIBLING" & audio_video == "audio") %>%
  mutate(MeanN = mean(n),
         TotalN = sum(n)) %>%
  filter(month == 17)

wilcox.test(
  x = subset(speaker.type.SIB_audio, SibGroup == "2+")$MeanN
  , y = subset(speaker.type.SIB_audio, SibGroup == "One")$MeanN
  , paired = FALSE
) # NS


# Difference in amount of input from mothers

speaker.type.MOT_audio <- speaker.type %>% group_by(subj) %>% 
  filter(Speaker == "MOT" & audio_video == "video") %>%
  mutate(MeanN = mean(n))  %>%
  filter(month == 17)

wilcox.test(
  x = subset(speaker.type.MOT_audio, SibGroup == "None")$MeanN
  , y = subset(speaker.type.MOT_audio, SibGroup == "One")$MeanN
  , paired = FALSE
) # NS

wilcox.test(
  x = subset(speaker.type.MOT_audio, SibGroup == "2+")$MeanN
  , y = subset(speaker.type.MOT_audio, SibGroup == "One")$MeanN
  , paired = FALSE
) # p<.001

```

### Object presence

```{r Object.presence summary}

object.presence.summary_audio <- object.presence %>%
  filter(audio_video == "audio") %>%
  group_by(subj, SibGroup) %>%
  summarise(mean.object = mean(PC),
            sd.object = sd(PC),
            med.object = median(PC))

```

```{r object.presence model}

object.presence.model_audio <- lmerTest::lmer(PC ~ SibGroup + month + (1|subj), data=subset(object.presence, audio_video == "audio"), REML=FALSE)
object.presence.model.null_audio <- lmerTest::lmer(PC ~ month + (1|subj), data=subset(object.presence, audio_video == "audio"), REML=FALSE)
anova(object.presence.model_audio, object.presence.model.null_audio) # p<.001

# Posthoc tests

wilcox.test(
  x = subset(object.presence.summary_audio, SibGroup == "None")$mean.object
  , y = subset(object.presence.summary_audio, SibGroup == "One")$mean.object
  , paired = FALSE
) # p<.05

wilcox.test(
  x = subset(object.presence.summary_audio, SibGroup == "2+")$mean.object
  , y = subset(object.presence.summary_audio, SibGroup == "One")$mean.object
  , paired = FALSE
) # p<.01

```

# Running all analyses with one twin removed

``` {r filter data}

SiblingsData_twin <- SiblingsData %>% filter(!subj %in% c(351, 794) & !month %in% c("06", "07", "08", "09"))
CDI_twin <- CDI %>% filter(!subj %in% c(424, 351, 794) )
speaker.type_twin <- speaker.type %>% filter(!subj %in% c(351, 794) & !month %in% c("06", "07", "08", "09"))
object.presence_twin <- object.presence %>% filter(!subj %in% c(351, 794) & !month %in% c("06", "07", "08", "09"))

```


```{r Overall vocab}

# SibGroup: Does having more vs. fewer vs. no siblings affect language development over time?

sibgroup.model_twin <- lmerTest::lmer(Log.Totalwords ~ SibGroup + month + (1|subj), data = SiblingsData_twin, REML=FALSE)
sibgroup.model.null_twin <- lmerTest::lmer(Log.Totalwords ~ month + (1|subj), data = SiblingsData_twin, REML=FALSE)
anova(sibgroup.model_twin, sibgroup.model.null_twin) %>%  # p<.05
  rename("pval" = `Pr(>Chisq)`)

```
### Parental Input

```{r speaker.type model, message=FALSE, warning=FALSE}

#shapiro.test(speaker.type$n) # not normal

speaker.type.model_twin <- lmerTest::lmer(Log.n ~ SibGroup + Speaker + (1|subj), data=subset(speaker.type_twin, audio_video == "video"), REML=FALSE)
speaker.type.model.null_twin <- lmerTest::lmer(Log.n ~ Speaker + (1|subj), data=subset(speaker.type_twin, audio_video == "video"), REML=FALSE)

anova(speaker.type.model_twin, speaker.type.model.null_twin) %>%
  rename("pval" = `Pr(>Chisq)`) # p<.01

# post hoc comparisons

speaker.type.mean_twin <- speaker.type_twin %>% 
  filter(audio_video == "video" & Speaker == "Family.input") %>%
  group_by(subj) %>% 
  mutate(MeanN = mean(n)) %>%
  filter(month == 17)

wilcox.test(
  x = subset(speaker.type.mean_twin, SibGroup == "None" & audio_video == "video")$MeanN
  , y = subset(speaker.type.mean_twin, SibGroup == "One"  & audio_video == "video")$MeanN
  , paired = FALSE
)  # NS

wilcox.test(
  x = subset(speaker.type.mean_twin, SibGroup == "2+" & audio_video == "video")$MeanN
  , y = subset(speaker.type.mean_twin, SibGroup == "One" & audio_video == "video")$MeanN
  , paired = FALSE
)  # p < .001

```

```{r Sibling input, message=FALSE, warning=FALSE}

# Difference in amount of input from siblings

speaker.type.SIB_twin <- speaker.type_twin %>% group_by(subj) %>% 
  filter(Speaker == "SIBLING" & audio_video == "video") %>%
  mutate(MeanN = mean(n),
         TotalN = sum(n)) %>%
  filter(month == 17)

wilcox.test(
  x = subset(speaker.type.SIB_twin, SibGroup == "2+" & audio_video == "video")$MeanN
  , y = subset(speaker.type.SIB_twin, SibGroup == "One" & audio_video == "video")$MeanN
  , paired = FALSE
) # NS

# Difference in amount of input from mothers

speaker.type.MOT_twin <- speaker.type_twin %>% group_by(subj) %>% 
  filter(Speaker == "MOT" & audio_video == "video") %>%
  mutate(MeanN = mean(n))  %>%
  filter(month == 17)

wilcox.test(
  x = subset(speaker.type.MOT_twin, SibGroup == "None" & audio_video == "video")$MeanN
  , y = subset(speaker.type.MOT_twin, SibGroup == "One" & audio_video == "video")$MeanN
  , paired = FALSE
) # NS

wilcox.test(
  x = subset(speaker.type.MOT_twin, SibGroup == "2+" & audio_video == "video")$MeanN
  , y = subset(speaker.type.MOT_twin, SibGroup == "One" & audio_video == "video")$MeanN
  , paired = FALSE
) # p<.01

# Difference in amount of input from fathers

speaker.type.FAT_twin <- speaker.type_twin %>% group_by(subj) %>% 
  filter(Speaker == "FAT" & audio_video == "video") %>%
  mutate(MeanN = mean(n))  %>%
  filter(month == 17)

wilcox.test(
  x = subset(speaker.type.FAT_twin, SibGroup == "None" & audio_video == "video")$MeanN
  , y = subset(speaker.type.FAT_twin, SibGroup == "One" & audio_video == "video")$MeanN
  , paired = FALSE
) # NS

wilcox.test(
  x = subset(speaker.type.FAT_twin, SibGroup == "2+" & audio_video == "video")$MeanN
  , y = subset(speaker.type.FAT_twin, SibGroup == "One" & audio_video == "video")$MeanN
  , paired = FALSE
) # NS


```

### Object presence

```{r object.presence model}

object.presence.model_twin <- lmerTest::lmer(PC ~ SibGroup + month + (1|subj), data=subset(object.presence_twin,  audio_video == "video"), REML=FALSE)
object.presence.model.null_twin <- lmerTest::lmer(PC ~ month + (1|subj), data=subset(object.presence_twin,  audio_video == "video"), REML=FALSE)
anova(object.presence.model_twin, object.presence.model.null_twin) # p<.001

# Posthoc tests


object.presence.summary_twin <- object.presence_twin %>%
  filter(audio_video == "video") %>%
  group_by(subj, SibGroup) %>%
  summarise(mean.object = mean(PC),
            sd.object = sd(PC),
            med.object = median(PC))

wilcox.test(
  x = subset(object.presence.summary_twin, SibGroup == "None")$mean.object
  , y = subset(object.presence.summary_twin, SibGroup == "One")$mean.object
  , paired = FALSE)
 # p<.001

wilcox.test(
  x = subset(object.presence.summary_twin, SibGroup == "2+")$mean.object
  , y = subset(object.presence.summary_twin, SibGroup == "One")$mean.object
  , paired = FALSE
) # p<.05


```

# Discrete sibling  number


```{r Overall vocab: Discrete sibling number}

# Sibling number: Does number of siblings affect language development over time?

sibnumber.model <- lmerTest::lmer(Log.Totalwords ~ Siblings6 + month + (1|subj), data=SiblingsData, REML=FALSE)
sibnumber.model.null <- lmerTest::lmer(Log.Totalwords ~ month + (1|subj), data=SiblingsData, REML=FALSE)
anova(sibnumber.model, sibnumber.model.null) # significant

# summary(sibnumber.model) # for each increasing sibling, infants know 30% fewer words at 18m

```

### Parental Input

```{r speaker.type model, message=FALSE, warning=FALSE}

speaker.type.model_siblings <- lmerTest::lmer(Log.n ~ SibGroup + Speaker + (1|subj), 
                                              data=subset(speaker.type, audio_video == "video"), REML=FALSE)

speaker.type.model.null_siblings <- lmerTest::lmer(Log.n ~ Speaker + (1|subj), 
                                                   data=subset(speaker.type, audio_video == "video"), REML=FALSE)

anova(speaker.type.model_siblings, speaker.type.model.null_siblings) # ns

```

```{r Sibling input, message=FALSE, warning=FALSE}

# Difference in amount of input from siblings

speaker.type.SIB <- speaker.type %>% group_by(subj) %>% 
  filter(Speaker == "SIBLING" & audio_video == "video") %>%
  mutate(MeanN = mean(n),
         TotalN = sum(n)) %>%
  filter(month == 17)

wilcox.test(
  x = subset(speaker.type.SIB, Siblings6 == "0")$MeanN
  , y = subset(speaker.type.SIB, Siblings6 == "1")$MeanN
  , paired = FALSE
) # p<.001

wilcox.test(
  x = subset(speaker.type.SIB, Siblings6 == "2")$MeanN
  , y = subset(speaker.type.SIB, Siblings6 == "1")$MeanN
  , paired = FALSE
) # NS

wilcox.test(
  x = subset(speaker.type.SIB, Siblings6 == "2")$MeanN
  , y = subset(speaker.type.SIB, Siblings6 == "3")$MeanN
  , paired = FALSE
) # NS

wilcox.test(
  x = subset(speaker.type.SIB, Siblings6 == "3")$MeanN
  , y = subset(speaker.type.SIB, Siblings6 == "4")$MeanN
  , paired = FALSE
) # NS

# Difference in amount of input from mothers

speaker.type.MOT <- speaker.type %>% group_by(subj) %>% 
  filter(Speaker == "MOT" & audio_video == "video") %>%
  mutate(MeanN = mean(n))  %>%
  filter(month == 17)

wilcox.test(
  x = subset(speaker.type.MOT, Siblings6 == "0")$MeanN
  , y = subset(speaker.type.MOT, Siblings6 == "1")$MeanN
  , paired = FALSE
) # NS

wilcox.test(
  x = subset(speaker.type.MOT, Siblings6 == "2")$MeanN
  , y = subset(speaker.type.MOT, Siblings6 == "1")$MeanN
  , paired = FALSE
) # p<.01

wilcox.test(
  x = subset(speaker.type.MOT, Siblings6 == "2")$MeanN
  , y = subset(speaker.type.MOT, Siblings6 == "3")$MeanN
  , paired = FALSE
) # NS

wilcox.test(
  x = subset(speaker.type.MOT, Siblings6 == "3")$MeanN
  , y = subset(speaker.type.MOT, Siblings6 == "4")$MeanN
  , paired = FALSE
) # NS


```

### Object presence

```{r Object.presence summary}

object.presence.summary_siblings <- object.presence %>%
  filter(audio_video == "video") %>%
  group_by(subj, Siblings6) %>%
  summarise(mean.object = mean(PC),
            sd.object = sd(PC),
            med.object = median(PC))

```

```{r object.presence model}

object.presence.model_siblings <- lmerTest::lmer(PC ~ Siblings6 + month + (1|subj), 
                                                 data=subset(object.presence, audio_video == "video"), REML=FALSE)

object.presence.model.null_siblings <- lmerTest::lmer(PC ~ month + (1|subj), 
                                                      data=subset(object.presence, audio_video == "video"), REML=FALSE)

anova(object.presence.model_siblings, object.presence.model.null_siblings) # p<.001

# Posthoc tests

wilcox.test(
  x = subset(object.presence.summary_siblings, Siblings6 == "0")$mean.object
  , y = subset(object.presence.summary_siblings, Siblings6 == "1")$mean.object
  , paired = FALSE
) # p<.001

wilcox.test(
  x = subset(object.presence.summary_siblings, Siblings6 == "2")$mean.object
  , y = subset(object.presence.summary_siblings, Siblings6 == "1")$mean.object
  , paired = FALSE
) # p<.05

wilcox.test(
  x = subset(object.presence.summary_siblings, Siblings6 == "2")$mean.object
  , y = subset(object.presence.summary_siblings, Siblings6 == "3")$mean.object
  , paired = FALSE
) # NS

wilcox.test(
  x = subset(object.presence.summary_siblings, Siblings6 == "3")$mean.object
  , y = subset(object.presence.summary_siblings, Siblings6 == "4")$mean.object
  , paired = FALSE
) # NS

```
